# Generated by Django 3.2.16 on 2023-01-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0003_auto_20230120_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.recipe', verbose_name='Рецепт'),
        ),
    ]
