version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: boikodw11/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/django/
      - media_value:/app/media/django/
      - redoc:/app/docs/
    depends_on:
      - db

    env_file:
      - ./.env

  frontend:
    image: boikodw11/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/django/
      - media_value:/var/html/media/django/
    depends_on:
      - backend
    restart: always

volumes:
  db_value:
  static_value:
  media_value:
  redoc:
